// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Ecosystems/container-storage-modules/src/csm-dr/pkg/storage (interfaces: HealthChecker,ArrayList)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/array.go . HealthChecker,ArrayList
//

// Package mock_storage is a generated GoMock package.
package mock_storage

import (
	context "context"
	reflect "reflect"

	storage "github.com/Ecosystems/container-storage-modules/src/csm-dr/pkg/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockHealthChecker is a mock of HealthChecker interface.
type MockHealthChecker struct {
	ctrl     *gomock.Controller
	recorder *MockHealthCheckerMockRecorder
	isgomock struct{}
}

// MockHealthCheckerMockRecorder is the mock recorder for MockHealthChecker.
type MockHealthCheckerMockRecorder struct {
	mock *MockHealthChecker
}

// NewMockHealthChecker creates a new mock instance.
func NewMockHealthChecker(ctrl *gomock.Controller) *MockHealthChecker {
	mock := &MockHealthChecker{ctrl: ctrl}
	mock.recorder = &MockHealthCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthChecker) EXPECT() *MockHealthCheckerMockRecorder {
	return m.recorder
}

// IsOnline mocks base method.
func (m *MockHealthChecker) IsOnline(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsOnline", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsOnline indicates an expected call of IsOnline.
func (mr *MockHealthCheckerMockRecorder) IsOnline(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsOnline", reflect.TypeOf((*MockHealthChecker)(nil).IsOnline), ctx)
}

// MockArrayList is a mock of ArrayList interface.
type MockArrayList struct {
	ctrl     *gomock.Controller
	recorder *MockArrayListMockRecorder
	isgomock struct{}
}

// MockArrayListMockRecorder is the mock recorder for MockArrayList.
type MockArrayListMockRecorder struct {
	mock *MockArrayList
}

// NewMockArrayList creates a new mock instance.
func NewMockArrayList(ctrl *gomock.Controller) *MockArrayList {
	mock := &MockArrayList{ctrl: ctrl}
	mock.recorder = &MockArrayListMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArrayList) EXPECT() *MockArrayListMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockArrayList) Get(arrayID string) (storage.HealthChecker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arrayID)
	ret0, _ := ret[0].(storage.HealthChecker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockArrayListMockRecorder) Get(arrayID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockArrayList)(nil).Get), arrayID)
}
