apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  - apiGroups:
      - dr.storage.dell.com
    resources:
      - volumejournals
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - dr.storage.dell.com
    resources:
      - volumejournals/finalizers
    verbs:
      - update
  - apiGroups:
      - dr.storage.dell.com
    resources:
      - volumejournals/status
    verbs:
      - get
      - patch
      - update
